FIX Prevent double escaping
silverstripe/cow pull request #208
Opened 2022-05-18 07:16 UTC by emteknetnz

Issue https://github.com/silverstripe/cow/issues/199

2022-05-18 23:18 UTC, GuySartorelli requested changes
This used to be _triple_ escaping, and is now _double_ escaping characters.

`>` gets escaped to `&gt;` which gets escaped to `&amp;gt;` which prior to this PR was further escaped to `&amp;amp;gt;`

> `Update README&amp;lt;a&amp;gt;my html&amp;lt;/a&amp;gt; lorem (Aaron Carlino)`

This is still going to display in the changelog, once rendered in the browser, as `Update README&lt;a&gt;my html&lt;/a&gt; lorem (Aaron Carlino)`

Caused by https://github.com/silverstripe/cow/blob/79dccf31af69006188b02321b47ab7c2d055f008/src/Model/Changelog/ChangelogItem.php#L244 which explains why other characters (such as `'`) are only escaped once after this PR.

2022-05-19 01:08 UTC, emteknetnz commented
Opps, pretty obvious error on my part.  Cheers for pointing out.  Have fixed up.

2022-05-19 01:09 UTC, GuySartorelli approved these changes

2022-05-19 01:09 UTC, GuySartorelli commented
Merge on green

2022-05-19 02:11 UTC, merged